### ISSUE TITLE
Themed Title Bar

### ISSUE THREAD

**Issue by tomcwatts** [dracula/sublime#9]
As of build 3127 Sublime supports theming for the title bar on OSX 10.10+. Any chance this could be added to the Dracula theme for sublime?

Official documentation:
http://www.sublimetext.com/docs/3/themes.html#elements-windows

**Comment by lotfio-lakehal** [comment]
hey zeno i really like your Color Scheme and i just want to suggest a small improvement if you don't mind :) just a different color for the reserved keyword **this  $this**   something like orange would be amazing

**Comment by zenorocha** [comment]
Hey guys, could you send a pull request? Thanks!

**Comment by rajasimon** [comment]
Why this still opened? Any progress on the side bar thing?

**Comment by rajasimon** [comment]
Waiting for the next release contain side bar and full dracula theme like Vscode dracula

**Comment by rajasimon** [comment]
@zenorocha Is any plan to merge #8 and update the theme to 2.0 using the new Dracula spec.

**Comment by zenorocha** [comment]
I think updating this color scheme to the new spec is more important then turning it into a full theme. This is because the new Sublime comes with an "Adaptive" theme that looks like this:

<img width="1552" alt="screen shot 2017-05-30 at 2 45 40 pm" src="https://cloud.githubusercontent.com/assets/398893/26606454/d281cfee-4546-11e7-91bd-24f0929c59ee.png">
